/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import data.Filtro;
import data.Vendas;
import data.VendasDao;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Samuel
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        preencherData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnInicio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbVendas = new javax.swing.JTable();
        Pnfiltro = new javax.swing.JPanel();
        LbFiltro = new javax.swing.JLabel();
        FfDataIni = new javax.swing.JFormattedTextField();
        FfDatafin = new javax.swing.JFormattedTextField();
        Lbe = new javax.swing.JLabel();
        Lbentree = new javax.swing.JLabel();
        LbCliente = new javax.swing.JLabel();
        TxCliente = new javax.swing.JTextField();
        LbProduto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CbProduto = new javax.swing.JComboBox<>();
        CbFormapg = new javax.swing.JComboBox<>();
        CbVendedor = new javax.swing.JComboBox<>();
        BtFiltrar = new javax.swing.JButton();
        CbSaldo = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        LbInicio = new javax.swing.JLabel();
        LbImagemFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        MIVenda = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        PnInicio.setPreferredSize(new java.awt.Dimension(120, 880));
        PnInicio.setLayout(null);

        TbVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Data", "Cliente", "Produto", "Qtd", "Valor", "Vendedor", "Forma pg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbVendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbVendas);

        PnInicio.add(jScrollPane1);
        jScrollPane1.setBounds(20, 260, 710, 230);

        Pnfiltro.setBackground(new java.awt.Color(153, 153, 153,150));
        Pnfiltro.setForeground(new java.awt.Color(255, 255, 255,100));

        LbFiltro.setBackground(new java.awt.Color(255, 255, 255));
        LbFiltro.setForeground(new java.awt.Color(255, 255, 255));
        LbFiltro.setText("Filtros:");

        try {
            FfDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            FfDatafin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FfDatafin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FfDatafinActionPerformed(evt);
            }
        });

        Lbe.setText("e");

        Lbentree.setForeground(new java.awt.Color(255, 255, 255));
        Lbentree.setText("entre:");

        LbCliente.setForeground(new java.awt.Color(255, 255, 255));
        LbCliente.setText("Cliente:");

        TxCliente.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxClienteCaretUpdate(evt);
            }
        });
        TxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxClienteActionPerformed(evt);
            }
        });

        LbProduto.setForeground(new java.awt.Color(255, 255, 255));
        LbProduto.setText("Vendedor:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Produto:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Forma de pagamento:");

        CbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Caixinha", "Bombom" }));

        CbFormapg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Pix", "Dinheiro", "Cartão" }));

        CbVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Samuel", "Luana" }));

        BtFiltrar.setBackground(new java.awt.Color(0, 102, 102));
        BtFiltrar.setForeground(new java.awt.Color(204, 204, 204));
        BtFiltrar.setText("Filtrar");
        BtFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFiltrarActionPerformed(evt);
            }
        });
        BtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtFiltrarKeyPressed(evt);
            }
        });

        CbSaldo.setForeground(new java.awt.Color(255, 255, 255));
        CbSaldo.setText("Saldo negativo");
        CbSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnfiltroLayout = new javax.swing.GroupLayout(Pnfiltro);
        Pnfiltro.setLayout(PnfiltroLayout);
        PnfiltroLayout.setHorizontalGroup(
            PnfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnfiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnfiltroLayout.createSequentialGroup()
                        .addGroup(PnfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbFiltro)
                            .addGroup(PnfiltroLayout.createSequentialGroup()
                                .addComponent(LbCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnfiltroLayout.createSequentialGroup()
                                .addComponent(Lbentree)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FfDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lbe, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FfDatafin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(PnfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnfiltroLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(CbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(LbProduto)
                                .addGap(18, 18, 18)
                                .addComponent(CbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(PnfiltroLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(CbFormapg, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PnfiltroLayout.createSequentialGroup()
                        .addComponent(CbSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtFiltrar)
                        .addGap(78, 78, 78))))
        );
        PnfiltroLayout.setVerticalGroup(
            PnfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnfiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FfDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FfDatafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbe)
                    .addComponent(Lbentree)
                    .addComponent(jLabel2)
                    .addComponent(LbProduto)
                    .addComponent(CbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCliente)
                    .addComponent(TxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(CbFormapg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PnfiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnfiltroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CbSaldo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnfiltroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtFiltrar)
                        .addGap(38, 38, 38))))
        );

        PnInicio.add(Pnfiltro);
        Pnfiltro.setBounds(20, 90, 710, 150);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LbInicio.setBackground(new java.awt.Color(0, 0, 0));
        LbInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LbInicio.setForeground(new java.awt.Color(0, 0, 0));
        LbInicio.setText("Tela inicio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PnInicio.add(jPanel1);
        jPanel1.setBounds(320, 10, 120, 50);

        LbImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemFundo/imagem f.png"))); // NOI18N
        PnInicio.add(LbImagemFundo);
        LbImagemFundo.setBounds(0, 0, 750, 500);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setForeground(new java.awt.Color(0, 0, 0));
        Menu.setText("Opções");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        MIVenda.setText("+ Venda");
        MIVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIVendaActionPerformed(evt);
            }
        });
        Menu.add(MIVenda);

        jMenuItem2.setText("Cálculos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem2);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MIVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIVendaActionPerformed
        
        TelaVendas v = new TelaVendas();
        v.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_MIVendaActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        
    }//GEN-LAST:event_MenuActionPerformed
     Filtro fil = new Filtro();
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaCalculos c = new TelaCalculos();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void CbSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbSaldoActionPerformed

    private void BtFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFiltrarActionPerformed

        String dataIni = FfDataIni.getText();
        String dataFin = FfDatafin.getText();
        String Cliente = TxCliente.getText();
        String Vendedor = String.valueOf(CbVendedor.getSelectedItem());
        String Produto = String.valueOf(CbProduto.getSelectedItem());
        String Formapg = String.valueOf(CbFormapg.getSelectedItem());
        boolean saldo = CbSaldo.isSelected();

        fil.setCliente(Cliente);
        fil.setFormapg(Formapg);
        fil.setProduto(Produto);
        fil.setVendedor(Vendedor);
        fil.setSaldo(saldo);

        SimpleDateFormat conversor = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date dataConvertida = conversor.parse(dataIni);
            java.sql.Date sqlDate = new java.sql.Date(dataConvertida.getTime());
            Date dataConvertida2 = conversor.parse(dataFin);
            java.sql.Date  sqlDate2 = new java.sql.Date(dataConvertida2.getTime());
            fil.setDataini(sqlDate);
            fil.setDatafin(sqlDate2);

        } catch (ParseException ex) {
            System.out.println("Erro na conversao da data " + ex.getMessage());
        }
        preencherTabela();
    }//GEN-LAST:event_BtFiltrarActionPerformed

    private void TxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxClienteActionPerformed

    private void TxClienteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxClienteCaretUpdate

    }//GEN-LAST:event_TxClienteCaretUpdate

    private void FfDatafinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FfDatafinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FfDatafinActionPerformed

    private void TbVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbVendasMouseClicked

        Vendas v = new Vendas();
        VendasDao dao = new VendasDao();
        int selecionado = TbVendas.getSelectedRow();
        int botao = evt.getButton();

        if(selecionado >= 0 && botao == 3){
            int opcao = JOptionPane.showConfirmDialog(null,"Deseja alterar ?");
            if(opcao == 0){
                boolean con = dao.Conectar();
                if(con == false){
                    JOptionPane.showMessageDialog(null,"Erro ao conectar com banco de dados");
                }else{
                    v = dao.Consultar(pegarId());
                    int id = v.getId();
                    String data = formataData(v.getData().toString().replace("/", ""));
                    String c = v.getCliente();
                    String p = v.getProduto();
                    String ven = v.getVendedor();
                    String fpg = v.getFormaPg();
                    String qtd = v.getQuantidade().toString();
                    String valor = v.getValor().toString();

                    TelaVendas tv = new TelaVendas();
                    tv.preencherDados(id, data, c, p, qtd, valor, ven, fpg);
                    tv.setVisible(true);
                    dispose();
                }
                dao.desconectar();
            }else if(opcao > 0){
                System.out.println("Operação cancelada");
            }

        }else{

        }

    }//GEN-LAST:event_TbVendasMouseClicked

    private void BtFiltrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtFiltrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtFiltrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtFiltrar;
    private javax.swing.JComboBox<String> CbFormapg;
    private javax.swing.JComboBox<String> CbProduto;
    private javax.swing.JCheckBox CbSaldo;
    private javax.swing.JComboBox<String> CbVendedor;
    private javax.swing.JFormattedTextField FfDataIni;
    private javax.swing.JFormattedTextField FfDatafin;
    private javax.swing.JLabel LbCliente;
    private javax.swing.JLabel LbFiltro;
    private javax.swing.JLabel LbImagemFundo;
    private javax.swing.JLabel LbInicio;
    private javax.swing.JLabel LbProduto;
    private javax.swing.JLabel Lbe;
    private javax.swing.JLabel Lbentree;
    private javax.swing.JMenuItem MIVenda;
    private javax.swing.JMenu Menu;
    private javax.swing.JPanel PnInicio;
    private javax.swing.JPanel Pnfiltro;
    private javax.swing.JTable TbVendas;
    private javax.swing.JTextField TxCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

     public String formataData(String data) {
        //aaaa-mm-dd
        String dia = data.substring(8);
        String mes = data.substring(5, 7);
        String ano = data.substring(0, 4);

        return dia + "/" + mes + "/" + ano;
    }
    
    
     public void preencherData(){
         DateTimeFormatter dt =  DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDateTime time = LocalDateTime.now();
            FfDataIni.setText(time.format(dt));
            FfDatafin.setText(time.format(dt));
            
        
     }
    
    
    public void preencherTabela(){
          VendasDao dao = new VendasDao();

        boolean status = dao.Conectar();

        if (status == false) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar conectar com o banco de dados ");
        } else {

            List<Vendas> listaVendas = dao.listaVenda(fil);
            DefaultTableModel tabelaFilmes = (DefaultTableModel) TbVendas.getModel();
            TbVendas.setRowSorter(new TableRowSorter(tabelaFilmes));
            tabelaFilmes.setNumRows(0);

            for (Vendas V : listaVendas) {
                Object[] obj = new Object[]{
                    V.getId(),
                    formataData(String.valueOf(V.getData())),                  
                    V.getCliente(),
                    V.getProduto(),
                    V.getQuantidade().toString().replace(".0",""),
                    V.getValor().toString().replace(".",",0"),
                    V.getVendedor(),
                    V.getFormaPg()
                };
                tabelaFilmes.addRow(obj);
                
              
            }
           
            

        }
        dao.desconectar();
             
         
    }
    
     public int pegarId(){
         int linha = TbVendas.getSelectedRow();
         
         String info = TbVendas.getValueAt(linha, 0).toString();       
         int id = Integer.parseInt(info);
         return id;
     }
    
    
    public void lerArquivo(){
    
          try{
            
            File obj = new File("C://teste//arquivo2.txt");
            
            Scanner leitura = new Scanner(obj);
            while(leitura.hasNextLine() ) {
            String data = leitura.nextLine();
        }
            leitura.close();
            
            
        }catch(FileNotFoundException FE){
            System.out.println("Erro gerado "+ FE.getMessage() );
    
        }
       }
    
}
